name: Post Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: products-ui-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  publish-products-ui-consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-latest

    name: Publish and tag products-ui consumer pact
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Parse Node version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: parse-node-version
      - name: Setup
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: "${{ steps.parse-node-version.outputs.NVMRC }}"
      - name: Cache build directories
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache pacts directory
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag products-ui consumer pact
        env:
          PACT_BROKER_URL: https://pay-pact-broker.cloudapps.digital
          PACT_CONSUMER_VERSION: ${{ github.sha }}
          PACT_BROKER_USERNAME: ${{ secrets.pact_broker_username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact_broker_password }}
          PACT_CONSUMER_TAG: master
        run: npm run publish-pacts

  adminusers-provider-contract-tests:
    needs: publish-products-ui-consumer-contract-tests
    uses: alphagov/pay-adminusers/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: products-ui
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  products-provider-contract-tests:
    needs: publish-products-ui-consumer-contract-tests
    uses: alphagov/pay-products/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: products-ui
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - adminusers-provider-contract-tests
      - products-provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
