name: Github Actions Tests

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    name: Unit tests

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup
        uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7
        with:
          node-version: 12.22.10
      - name: Cache NPM packages
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run lint
        run: npm run lint
      - name: Run unit tests
        run: npm test -- --forbid-only --forbid-pending
