name: Github Actions Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-18.04
    name: Parse versions
    outputs:
      node-version: ${{ steps.parse-node-version.outputs.nvmrc }}
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Parse Node version
        id: parse-node-version
        run: echo "##[set-output name=nvmrc;]$(cat .nvmrc)" 
  install-and-compile:
    runs-on: ubuntu-18.04
    name: Install and compile
    needs: version

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Setup
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ needs.version.outputs.node-version }}
      - name: Parse Cypress version
        id: parse-cypress-version
        run: echo "::set-output name=CYPRESS_VERSION::$(jq -r '.devDependencies.cypress' package.json)"
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run lint
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-18.04
    name: Unit tests
    needs: [version, install-and-compile]

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Setup
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ needs.version.outputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run unit tests
        run: npm test -- --forbid-only --forbid-pending

  cypress-tests:
    runs-on: ubuntu-18.04
    name: Cypress tests
    needs: [version, install-and-compile]

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Setup
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: ${{ needs.version.outputs.node-version }}
      - name: Parse Cypress version
        id: parse-cypress-version
        run: echo "::set-output name=CYPRESS_VERSION::$(jq -r '.devDependencies.cypress' package.json)"
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run cypress tests
        run: |
          npm run cypress:server > /dev/null 2>&1 &
          sleep 3
          npm run cypress:test
